name: loader-service

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd loader-service
        make install

    - name: Run Lint
      run: |
        cd loader-service
        make lint

    - name: Run tests
      run: |
        cd loader-service
        make test

    - name: Format
      run: |
        cd loader-service
        make format
